# 1. 데이터 프레임 스케일링

In [43]:
import os
import sys
import pandas as pd
import numpy as np

In [44]:
pwd

'C:\\Users\\eunwon\\Desktop\\multi\\Project\\강서구'

In [45]:
df = pd.read_excel('강서구_power bi.xlsx')
df

,행정동,체육시설,도서관,문화시설,공원,장애인복지시설,어르신돌봄시설,경로당,사회복지시설,전통시장,...,투룸.쓰리룸(보증금),투룸.쓰리룸(월세),오피스텔/도시형생활주택(보증금),오피스텔/도시형생활주택(월세),아파트(보증금),아파트(월세),원룸(전세),투룸.쓰리룸(전세),오피스텔/도시형생활주택(전세),아파트(전세)
0,염창동,0,1,0,0,0,0,36,1,0,...,3000,72,4000,70,29800,115,11000,28700,28200,66545
1,등촌1동,0,0,0,0,0,1,14,6,1,...,1000,103,2000,108,32772,82,11800,20470,26800,48848
2,등촌2동,0,1,0,0,0,1,8,3,0,...,1000,103,2000,108,32772,82,11800,20470,26800,48848
3,등촌3동,1,1,0,0,3,5,16,26,0,...,1000,103,2000,108,32772,82,11800,20470,26800,48848
4,화곡1동,0,0,0,0,1,0,7,13,2,...,5000,48,5000,48,32300,90,12600,19300,19100,48194
5,화곡2동,0,0,0,0,0,0,2,5,0,...,5000,48,5000,48,32300,90,12600,19300,19100,48194
6,화곡3동,0,2,0,4,0,1,5,3,1,...,5000,48,5000,48,32300,90,12600,19300,19100,48194
7,화곡4동,0,0,0,0,0,0,4,3,2,...,5000,48,5000,48,32300,90,12600,19300,19100,48194
8,화곡본동,0,0,1,1,1,1,5,22,1,...,5000,48,5000,48,32300,90,12600,19300,19100,48194
9,화곡6동,0,0,0,0,7,1,7,13,0,...,5000,48,5000,48,32300,90,12600,19300,19100,48194
10,화곡8동,0,0,0,0,0,0,5,8,1,...,5000,48,5000,48,32300,90,12600,19300,19100,48194
11,가양1동,2,0,3,1,4,0,16,6,0,...,5000,135,2000,69,41690,108,16200,18800,20200,67743
12,가양2동,0,0,1,0,3,1,6,11,0,...,5000,135,2000,69,41690,108,16200,18800,20200,67743
13,가양3동,1,0,0,0,0,0,8,1,0,...,5000,135,2000,69,41690,108,16200,18800,20200,67743
14,발산1동,0,0,0,0,1,0,11,12,1,...,0,0,0,0,0,0,0,0,0,0
15,우장산동,1,1,2,0,2,0,8,12,0,...,3000,70,0,0,35700,105,12500,19100,31900,50287
16,공항동,1,1,0,0,2,0,10,10,0,...,200,73,1000,56,3500,90,9600,19700,9700,59500
17,방화1동,0,0,0,0,3,1,25,13,1,...,2000,95,1300,36,0,0,7100,20000,8950,0
18,방화2동,2,0,0,0,4,0,11,12,1,...,2000,95,1300,36,0,0,7100,20000,8950,0
19,방화3동,0,2,0,0,0,0,16,4,0,...,2000,95,1300,36,0,0,7100,20000,8950,0

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   행정동                20 non-null     object
 1   체육시설               20 non-null     int64
 2   도서관                20 non-null     int64
 3   문화시설               20 non-null     int64
 4   공원                 20 non-null     int64
 5   장애인복지시설            20 non-null     int64
 6   어르신돌봄시설            20 non-null     int64
 7   경로당                20 non-null     int64
 8   사회복지시설             20 non-null     int64
 9   전통시장               20 non-null     int64
 10  백화점                20 non-null     int64
 11  대형마트&슈퍼마켓          20 non-null     int64
 12  편의점                20 non-null     int64
 13  세탁소                20 non-null     int64
 14  식당                 20 non-null     int64
 15  카페                 20 non-null     int64
 16  헬스클럽               20 non-null     int64
 17  영화관                20 non-null     int64
 18  구청,동주민센터,보건소       20 non-null     int64
 19  공영주차장              20 non-null     int64
 20  버스정류장              20 non-null     int64
 21  공공자전거 대여소          20 non-null     int64
 22  파출소                20 non-null     int64
 23  여성안심택배함            20 non-null     int64
 24  심리상담센터             20 non-null     int64
 25  병원                 20 non-null     int64
 26  CCTV               20 non-null     int64
 27  개등록수               20 non-null     int64
 28  고양이등록수             20 non-null     int64
 29  동물병원               20 non-null     int64
 30  원룸(보증금)            20 non-null     int64
 31  원룸(월세)             20 non-null     int64
 32  투룸.쓰리룸(보증금)        20 non-null     int64
 33  투룸.쓰리룸(월세)         20 non-null     int64
 34  오피스텔/도시형생활주택(보증금)  20 non-null     int64
 35  오피스텔/도시형생활주택(월세)   20 non-null     int64
 36  아파트(보증금)           20 non-null     int64
 37  아파트(월세)            20 non-null     int64
 38  원룸(전세)             20 non-null     int64
 39  투룸.쓰리룸(전세)         20 non-null     int64
 40  오피스텔/도시형생활주택(전세)   20 non-null     int64
 41  아파트(전세)            20 non-null     int64
dtypes: int64(41), object(1)
memory usage: 6.7+ KB

## 1. minmax sacler

In [47]:
# minmax scaling : 최소값 0, 최대값 1로 정규화
# 비교적 직관적이지만 이상치에 영향을 많이 받음

In [48]:
from sklearn.preprocessing import MinMaxScaler

# Normalization 최소값 0 / 최대값 1
scaler = MinMaxScaler()

# 행정동 컬럼 제외
minmax_trans = pd.DataFrame(scaler.fit_transform(df.iloc[:,1:]))
minmax_trans

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,0.0,0.5,0.000000,0.00,0.000000,0.0,1.000000,0.00,0.0,0.0,...,0.60,0.533333,0.80,0.648148,0.714800,1.000000,0.679012,1.000000,0.884013,0.982316
1,0.0,0.0,0.000000,0.00,0.000000,0.2,0.352941,0.20,0.5,0.0,...,0.20,0.762963,0.40,1.000000,0.786088,0.713043,0.728395,0.713240,0.840125,0.721078
2,0.0,0.5,0.000000,0.00,0.000000,0.2,0.176471,0.08,0.0,0.0,...,0.20,0.762963,0.40,1.000000,0.786088,0.713043,0.728395,0.713240,0.840125,0.721078
3,0.5,0.5,0.000000,0.00,0.428571,1.0,0.411765,1.00,0.0,1.0,...,0.20,0.762963,0.40,1.000000,0.786088,0.713043,0.728395,0.713240,0.840125,0.721078
4,0.0,0.0,0.000000,0.00,0.142857,0.0,0.147059,0.48,1.0,0.0,...,1.00,0.355556,1.00,0.444444,0.774766,0.782609,0.777778,0.672474,0.598746,0.711424
5,0.0,0.0,0.000000,0.00,0.000000,0.0,0.000000,0.16,0.0,0.0,...,1.00,0.355556,1.00,0.444444,0.774766,0.782609,0.777778,0.672474,0.598746,0.711424
6,0.0,1.0,0.000000,1.00,0.000000,0.2,0.088235,0.08,0.5,0.0,...,1.00,0.355556,1.00,0.444444,0.774766,0.782609,0.777778,0.672474,0.598746,0.711424
7,0.0,0.0,0.000000,0.00,0.000000,0.0,0.058824,0.08,1.0,0.0,...,1.00,0.355556,1.00,0.444444,0.774766,0.782609,0.777778,0.672474,0.598746,0.711424
8,0.0,0.0,0.333333,0.25,0.142857,0.2,0.088235,0.84,0.5,0.0,...,1.00,0.355556,1.00,0.444444,0.774766,0.782609,0.777778,0.672474,0.598746,0.711424
9,0.0,0.0,0.000000,0.00,1.000000,0.2,0.147059,0.48,0.0,0.0,...,1.00,0.355556,1.00,0.444444,0.774766,0.782609,0.777778,0.672474,0.598746,0.711424
10,0.0,0.0,0.000000,0.00,0.000000,0.0,0.088235,0.28,0.5,0.0,...,1.00,0.355556,1.00,0.444444,0.774766,0.782609,0.777778,0.672474,0.598746,0.711424
11,1.0,0.0,1.000000,0.25,0.571429,0.0,0.411765,0.20,0.0,0.0,...,1.00,1.000000,0.40,0.638889,1.000000,0.939130,1.000000,0.655052,0.633229,1.000000
12,0.0,0.0,0.333333,0.00,0.428571,0.2,0.117647,0.40,0.0,0.0,...,1.00,1.000000,0.40,0.638889,1.000000,0.939130,1.000000,0.655052,0.633229,1.000000
13,0.5,0.0,0.000000,0.00,0.000000,0.0,0.176471,0.00,0.0,0.0,...,1.00,1.000000,0.40,0.638889,1.000000,0.939130,1.000000,0.655052,0.633229,1.000000
14,0.0,0.0,0.000000,0.00,0.142857,0.0,0.264706,0.44,0.5,0.0,...,0.00,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.5,0.5,0.666667,0.00,0.285714,0.0,0.176471,0.44,0.0,0.0,...,0.60,0.518519,0.00,0.000000,0.856320,0.913043,0.771605,0.665505,1.000000,0.742320
16,0.5,0.5,0.000000,0.00,0.285714,0.0,0.235294,0.36,0.0,1.0,...,0.04,0.540741,0.20,0.518519,0.083953,0.782609,0.592593,0.686411,0.304075,0.878320
17,0.0,0.0,0.000000,0.00,0.428571,0.2,0.676471,0.48,0.5,0.0,...,0.40,0.703704,0.26,0.333333,0.000000,0.000000,0.438272,0.696864,0.280564,0.000000
18,1.0,0.0,0.000000,0.00,0.571429,0.0,0.264706,0.44,0.5,0.0,...,0.40,0.703704,0.26,0.333333,0.000000,0.000000,0.438272,0.696864,0.280564,0.000000
19,0.0,1.0,0.000000,0.00,0.000000,0.0,0.411765,0.12,0.0,0.0,...,0.40,0.703704,0.26,0.333333,0.000000,0.000000,0.438272,0.696864,0.280564,0.000000

## 2. robust scaler

In [49]:
# Robust scaling :  중앙값 0, IQR 1이 되도록 스케일링하는 방법
# 최대, 최소값이 아닌 사분위수를 이용하기 때문에 이상치의 영향을 최소화 할 수 있다.

In [50]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

# 행정동 컬럼 제외
robust_trans = pd.DataFrame(scaler.fit_transform(df.iloc[:,1:]))
robust_trans

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,0.0,1.0,0.0,0.0,-0.333333,0.0,3.200000,-0.941176,0.0,0.0,...,-0.307692,-0.009091,0.540541,0.916667,-0.261862,2.127660,-0.794872,12.533333,1.784314,4.174239
1,0.0,0.0,0.0,0.0,-0.333333,1.0,0.685714,-0.352941,1.0,0.0,...,-0.923077,0.554545,0.000000,2.500000,0.049440,-0.680851,-0.384615,1.560000,1.509804,0.148763
2,0.0,1.0,0.0,0.0,-0.333333,1.0,0.000000,-0.705882,0.0,0.0,...,-0.923077,0.554545,0.000000,2.500000,0.049440,-0.680851,-0.384615,1.560000,1.509804,0.148763
3,1.0,1.0,0.0,0.0,0.666667,5.0,0.914286,2.000000,0.0,1.0,...,-0.923077,0.554545,0.000000,2.500000,0.049440,-0.680851,-0.384615,1.560000,1.509804,0.148763
4,0.0,0.0,0.0,0.0,0.000000,0.0,-0.114286,0.470588,2.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
5,0.0,0.0,0.0,0.0,-0.333333,0.0,-0.685714,-0.470588,0.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
6,0.0,2.0,0.0,4.0,-0.333333,1.0,-0.342857,-0.705882,1.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
7,0.0,0.0,0.0,0.0,-0.333333,0.0,-0.457143,-0.705882,2.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
8,0.0,0.0,1.0,1.0,0.000000,1.0,-0.342857,1.529412,1.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
9,0.0,0.0,0.0,0.0,2.000000,1.0,-0.114286,0.470588,0.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
10,0.0,0.0,0.0,0.0,-0.333333,0.0,-0.342857,-0.117647,1.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
11,2.0,0.0,3.0,1.0,1.000000,0.0,0.914286,-0.352941,0.0,0.0,...,0.307692,1.136364,0.000000,0.875000,0.983555,1.531915,1.871795,-0.666667,0.215686,4.446744
12,0.0,0.0,1.0,0.0,0.666667,1.0,-0.228571,0.235294,0.0,0.0,...,0.307692,1.136364,0.000000,0.875000,0.983555,1.531915,1.871795,-0.666667,0.215686,4.446744
13,1.0,0.0,0.0,0.0,-0.333333,0.0,0.000000,-0.941176,0.0,0.0,...,0.307692,1.136364,0.000000,0.875000,0.983555,1.531915,1.871795,-0.666667,0.215686,4.446744
14,0.0,0.0,0.0,0.0,0.000000,0.0,0.342857,0.352941,1.0,0.0,...,-1.230769,-1.318182,-0.540541,-2.000000,-3.383262,-7.659574,-6.435897,-25.733333,-3.745098,-10.962525
15,1.0,1.0,2.0,0.0,0.333333,0.0,0.000000,0.352941,0.0,0.0,...,-0.307692,-0.045455,-0.540541,-2.000000,0.356133,1.276596,-0.025641,-0.266667,2.509804,0.476088
16,1.0,1.0,0.0,0.0,0.333333,0.0,0.228571,0.117647,0.0,1.0,...,-1.169231,0.009091,-0.270270,0.333333,-3.016654,0.000000,-1.512821,0.533333,-1.843137,2.571737
17,0.0,0.0,0.0,0.0,0.666667,1.0,1.942857,0.470588,1.0,0.0,...,-0.615385,0.409091,-0.189189,-0.500000,-3.383262,-7.659574,-2.794872,0.933333,-1.990196,-10.962525
18,2.0,0.0,0.0,0.0,1.000000,0.0,0.342857,0.352941,1.0,0.0,...,-0.615385,0.409091,-0.189189,-0.500000,-3.383262,-7.659574,-2.794872,0.933333,-1.990196,-10.962525
19,0.0,2.0,0.0,0.0,-0.333333,0.0,0.914286,-0.588235,0.0,0.0,...,-0.615385,0.409091,-0.189189,-0.500000,-3.383262,-7.659574,-2.794872,0.933333,-1.990196,-10.962525

## 3. 데이터프레임 재구성 (robust 스케일링 결과로 진행)

In [51]:
# 컬럼명 다시 붙이기
a = df.columns
robust_trans.columns = a[1:]

# 행정동 인덱스로 넣기
robust_trans.index = df['행정동']

robust_trans

,체육시설,도서관,문화시설,공원,장애인복지시설,어르신돌봄시설,경로당,사회복지시설,전통시장,백화점,...,투룸.쓰리룸(보증금),투룸.쓰리룸(월세),오피스텔/도시형생활주택(보증금),오피스텔/도시형생활주택(월세),아파트(보증금),아파트(월세),원룸(전세),투룸.쓰리룸(전세),오피스텔/도시형생활주택(전세),아파트(전세)
행정동,,,,,,,,,,,,,,,,,,,,,
염창동,0.0,1.0,0.0,0.0,-0.333333,0.0,3.200000,-0.941176,0.0,0.0,...,-0.307692,-0.009091,0.540541,0.916667,-0.261862,2.127660,-0.794872,12.533333,1.784314,4.174239
등촌1동,0.0,0.0,0.0,0.0,-0.333333,1.0,0.685714,-0.352941,1.0,0.0,...,-0.923077,0.554545,0.000000,2.500000,0.049440,-0.680851,-0.384615,1.560000,1.509804,0.148763
등촌2동,0.0,1.0,0.0,0.0,-0.333333,1.0,0.000000,-0.705882,0.0,0.0,...,-0.923077,0.554545,0.000000,2.500000,0.049440,-0.680851,-0.384615,1.560000,1.509804,0.148763
등촌3동,1.0,1.0,0.0,0.0,0.666667,5.0,0.914286,2.000000,0.0,1.0,...,-0.923077,0.554545,0.000000,2.500000,0.049440,-0.680851,-0.384615,1.560000,1.509804,0.148763
화곡1동,0.0,0.0,0.0,0.0,0.000000,0.0,-0.114286,0.470588,2.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
화곡2동,0.0,0.0,0.0,0.0,-0.333333,0.0,-0.685714,-0.470588,0.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
화곡3동,0.0,2.0,0.0,4.0,-0.333333,1.0,-0.342857,-0.705882,1.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
화곡4동,0.0,0.0,0.0,0.0,-0.333333,0.0,-0.457143,-0.705882,2.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
화곡본동,0.0,0.0,1.0,1.0,0.000000,1.0,-0.342857,1.529412,1.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
화곡6동,0.0,0.0,0.0,0.0,2.000000,1.0,-0.114286,0.470588,0.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
화곡8동,0.0,0.0,0.0,0.0,-0.333333,0.0,-0.342857,-0.117647,1.0,0.0,...,0.307692,-0.445455,0.810811,0.000000,0.000000,0.000000,0.025641,0.000000,0.000000,0.000000
가양1동,2.0,0.0,3.0,1.0,1.000000,0.0,0.914286,-0.352941,0.0,0.0,...,0.307692,1.136364,0.000000,0.875000,0.983555,1.531915,1.871795,-0.666667,0.215686,4.446744
가양2동,0.0,0.0,1.0,0.0,0.666667,1.0,-0.228571,0.235294,0.0,0.0,...,0.307692,1.136364,0.000000,0.875000,0.983555,1.531915,1.871795,-0.666667,0.215686,4.446744
가양3동,1.0,0.0,0.0,0.0,-0.333333,0.0,0.000000,-0.941176,0.0,0.0,...,0.307692,1.136364,0.000000,0.875000,0.983555,1.531915,1.871795,-0.666667,0.215686,4.446744
발산1동,0.0,0.0,0.0,0.0,0.000000,0.0,0.342857,0.352941,1.0,0.0,...,-1.230769,-1.318182,-0.540541,-2.000000,-3.383262,-7.659574,-6.435897,-25.733333,-3.745098,-10.962525
우장산동,1.0,1.0,2.0,0.0,0.333333,0.0,0.000000,0.352941,0.0,0.0,...,-0.307692,-0.045455,-0.540541,-2.000000,0.356133,1.276596,-0.025641,-0.266667,2.509804,0.476088
공항동,1.0,1.0,0.0,0.0,0.333333,0.0,0.228571,0.117647,0.0,1.0,...,-1.169231,0.009091,-0.270270,0.333333,-3.016654,0.000000,-1.512821,0.533333,-1.843137,2.571737
방화1동,0.0,0.0,0.0,0.0,0.666667,1.0,1.942857,0.470588,1.0,0.0,...,-0.615385,0.409091,-0.189189,-0.500000,-3.383262,-7.659574,-2.794872,0.933333,-1.990196,-10.962525
방화2동,2.0,0.0,0.0,0.0,1.000000,0.0,0.342857,0.352941,1.0,0.0,...,-0.615385,0.409091,-0.189189,-0.500000,-3.383262,-7.659574,-2.794872,0.933333,-1.990196,-10.962525
방화3동,0.0,2.0,0.0,0.0,-0.333333,0.0,0.914286,-0.588235,0.0,0.0,...,-0.615385,0.409091,-0.189189,-0.500000,-3.383262,-7.659574,-2.794872,0.933333,-1.990196,-10.962525

# 2. numpy를 이용한 매트릭스 계산

In [52]:
robust_trans.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 염창동 to 방화3동
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   체육시설               20 non-null     float64
 1   도서관                20 non-null     float64
 2   문화시설               20 non-null     float64
 3   공원                 20 non-null     float64
 4   장애인복지시설            20 non-null     float64
 5   어르신돌봄시설            20 non-null     float64
 6   경로당                20 non-null     float64
 7   사회복지시설             20 non-null     float64
 8   전통시장               20 non-null     float64
 9   백화점                20 non-null     float64
 10  대형마트&슈퍼마켓          20 non-null     float64
 11  편의점                20 non-null     float64
 12  세탁소                20 non-null     float64
 13  식당                 20 non-null     float64
 14  카페                 20 non-null     float64
 15  헬스클럽               20 non-null     float64
 16  영화관                20 non-null     float64
 17  구청,동주민센터,보건소       20 non-null     float64
 18  공영주차장              20 non-null     float64
 19  버스정류장              20 non-null     float64
 20  공공자전거 대여소          20 non-null     float64
 21  파출소                20 non-null     float64
 22  여성안심택배함            20 non-null     float64
 23  심리상담센터             20 non-null     float64
 24  병원                 20 non-null     float64
 25  CCTV               20 non-null     float64
 26  개등록수               20 non-null     float64
 27  고양이등록수             20 non-null     float64
 28  동물병원               20 non-null     float64
 29  원룸(보증금)            20 non-null     float64
 30  원룸(월세)             20 non-null     float64
 31  투룸.쓰리룸(보증금)        20 non-null     float64
 32  투룸.쓰리룸(월세)         20 non-null     float64
 33  오피스텔/도시형생활주택(보증금)  20 non-null     float64
 34  오피스텔/도시형생활주택(월세)   20 non-null     float64
 35  아파트(보증금)           20 non-null     float64
 36  아파트(월세)            20 non-null     float64
 37  원룸(전세)             20 non-null     float64
 38  투룸.쓰리룸(전세)         20 non-null     float64
 39  오피스텔/도시형생활주택(전세)   20 non-null     float64
 40  아파트(전세)            20 non-null     float64
dtypes: float64(41)
memory usage: 6.6+ KB

In [53]:
matrix_df = robust_trans.to_numpy() # dataframe을 numpy array로 변환 (타겟 행렬 구성)
matrix_df

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  0.00000000e+00,
         3.20000000e+00, -9.41176471e-01,  0.00000000e+00,
         0.00000000e+00,  8.69565217e-01,  7.38461538e-01,
         8.69565217e-01, -2.62425447e-01,  1.74496644e-01,
         5.00000000e-01,  0.00000000e+00,  1.00000000e+00,
        -3.33333333e-01,  1.01265823e-01,  4.44444444e-01,
         5.00000000e-01, -5.00000000e-01,  6.15384615e-01,
         1.80790960e-01,  1.58139535e-01,  8.01284625e-01,
         8.75000000e-01,  5.00000000e-01, -1.60000000e+00,
        -8.00000000e-01, -3.07692308e-01, -9.09090909e-03,
         5.40540541e-01,  9.16666667e-01, -2.61862365e-01,
         2.12765957e+00, -7.94871795e-01,  1.25333333e+01,
         1.78431373e+00,  4.17423941e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  1.00000000e+00,
         6.85714286e-01, -3.52941176e-01,  1.00000000e+00,
         0.00000000e+00,  5.21739130e-01,  9.84615385e-01,
         5.21739130e-01,  1.43141153e-01,  4.96644295e-01,
         6.25000000e-01,  0.00000000e+00,  1.00000000e+00,
        -3.33333333e-01, -7.08860759e-01,  7.40740741e-01,
        -5.00000000e-01, -5.00000000e-01,  6.15384615e-01,
         6.77966102e-02, -5.86046512e-01, -1.28462465e-01,
         1.25000000e-01, -5.00000000e-01,  0.00000000e+00,
         2.00000000e-01, -9.23076923e-01,  5.54545455e-01,
         0.00000000e+00,  2.50000000e+00,  4.94396145e-02,
        -6.80851064e-01, -3.84615385e-01,  1.56000000e+00,
         1.50980392e+00,  1.48763150e-01],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  1.00000000e+00,
         0.00000000e+00, -7.05882353e-01,  0.00000000e+00,
         0.00000000e+00, -1.21739130e+00, -3.69230769e-01,
        -1.21739130e+00, -8.98608350e-01, -4.96644295e-01,
        -3.75000000e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.06329114e+00, -2.96296296e-01,
         5.00000000e-01, -5.00000000e-01, -6.15384615e-01,
        -8.58757062e-01, -1.58139535e-01, -7.19389803e-01,
        -3.75000000e-01, -5.00000000e-01,  0.00000000e+00,
         2.00000000e-01, -9.23076923e-01,  5.54545455e-01,
         0.00000000e+00,  2.50000000e+00,  4.94396145e-02,
        -6.80851064e-01, -3.84615385e-01,  1.56000000e+00,
         1.50980392e+00,  1.48763150e-01],
       [ 1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.66666667e-01,  5.00000000e+00,
         9.14285714e-01,  2.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  3.47826087e-01, -1.23076923e-01,
         3.47826087e-01,  5.00994036e-01,  3.08724832e-01,
         6.25000000e-01,  2.00000000e+00,  0.00000000e+00,
         3.33333333e-01,  1.01265823e+00,  0.00000000e+00,
         5.00000000e-01, -5.00000000e-01,  1.23076923e+00,
         8.36158192e-01, -5.86046512e-01,  1.92693697e-01,
         3.75000000e-01,  0.00000000e+00,  0.00000000e+00,
         2.00000000e-01, -9.23076923e-01,  5.54545455e-01,
         0.00000000e+00,  2.50000000e+00,  4.94396145e-02,
        -6.80851064e-01, -3.84615385e-01,  1.56000000e+00,
         1.50980392e+00,  1.48763150e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.14285714e-01,  4.70588235e-01,  2.00000000e+00,
         0.00000000e+00,  1.91304348e+00,  1.60000000e+00,
         1.91304348e+00,  1.67793241e+00,  5.50335570e-01,
         5.00000000e-01,  1.00000000e+00,  1.00000000e+00,
         1.66666667e+00, -1.51898734e-01,  0.00000000e+00,
         5.00000000e-01,  5.00000000e-01,  1.23076923e+00,
         1.58192090e+00,  2.68837209e+00,  3.61621839e+00,
         2.37500000e+00,  3.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.07692308e-01, -4.45454545e-01,
         8.10810811e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.56410256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  0.00000000e+00,
        -6.85714286e-01, -4.70588235e-01,  0.00000000e+00,
         0.00000000e+00, -1.73913043e-01, -4.92307692e-01,
        -1.73913043e-01, -1.05765408e+00, -6.57718121e-01,
        -3.75000000e-01,  0.00000000e+00, -1.00000000e+00,
        -3.33333333e-01,  1.01265823e-01, -5.92592593e-01,
        -5.00000000e-01, -5.00000000e-01, -6.15384615e-01,
        -7.45762712e-01, -9.30232558e-03, -2.00722601e-01,
        -1.25000000e-01, -5.00000000e-01,  0.00000000e+00,
         0.00000000e+00,  3.07692308e-01, -4.45454545e-01,
         8.10810811e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.56410256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  2.00000000e+00,  0.00000000e+00,
         4.00000000e+00, -3.33333333e-01,  1.00000000e+00,
        -3.42857143e-01, -7.05882353e-01,  1.00000000e+00,
         0.00000000e+00, -1.73913043e-01, -1.23076923e-01,
        -1.73913043e-01, -1.59045726e-02, -2.01342282e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -9.62025316e-01, -1.48148148e-01,
         5.00000000e-01,  5.00000000e-01, -3.07692308e-01,
         5.87570621e-01, -1.95348837e-01,  0.00000000e+00,
         1.25000000e-01, -1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.07692308e-01, -4.45454545e-01,
         8.10810811e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.56410256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  0.00000000e+00,
        -4.57142857e-01, -7.05882353e-01,  2.00000000e+00,
         0.00000000e+00, -3.47826087e-01, -1.23076923e-01,
        -3.47826087e-01,  1.59045726e-02, -2.55033557e-01,
        -1.25000000e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.06329114e-02, -7.40740741e-01,
         5.00000000e-01,  5.00000000e-01, -6.15384615e-01,
         0.00000000e+00,  7.16279070e-01,  0.00000000e+00,
         1.25000000e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.07692308e-01, -4.45454545e-01,
         8.10810811e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.56410256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        -3.42857143e-01,  1.52941176e+00,  1.00000000e+00,
         0.00000000e+00,  1.04347826e+00,  2.46153846e-01,
         1.04347826e+00, -3.18091451e-02, -6.04026846e-01,
        -6.25000000e-01,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00, -2.02531646e-01, -1.48148148e-01,
        -5.00000000e-01,  1.50000000e+00, -3.07692308e-01,
        -6.77966102e-02,  2.11162791e+00,  1.60738659e+00,
         1.12500000e+00,  5.00000000e-01,  0.00000000e+00,
         0.00000000e+00,  3.07692308e-01, -4.45454545e-01,
         8.10810811e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.56410256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        -1.14285714e-01,  4.70588235e-01,  0.00000000e+00,
         0.00000000e+00,  6.95652174e-01,  4.92307692e-01,
         6.95652174e-01,  8.82703777e-01, -1.34228188e-02,
         1.25000000e-01,  0.00000000e+00,  2.00000000e+00,
         1.00000000e+00,  5.06329114e-02,  1.48148148e-01,
         1.50000000e+00,  5.00000000e-01,  3.07692308e-01,
        -1.80790960e-01,  4.74418605e-01,  6.03773585e-01,
         3.75000000e-01,  5.00000000e-01,  0.00000000e+00,
         0.00000000e+00,  3.07692308e-01, -4.45454545e-01,
         8.10810811e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.56410256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  0.00000000e+00,
        -3.42857143e-01, -1.17647059e-01,  1.00000000e+00,
         0.00000000e+00,  1.73913043e-01, -1.23076923e-01,
         1.73913043e-01, -2.70377734e-01, -3.35570470e-01,
        -5.00000000e-01,  0.00000000e+00,  0.00000000e+00,
         2.33333333e+00, -1.01265823e-01, -5.92592593e-01,
        -5.00000000e-01,  2.50000000e+00, -3.07692308e-01,
         0.00000000e+00,  2.32558140e-01,  4.01445203e-01,
         3.75000000e-01, -1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.07692308e-01, -4.45454545e-01,
         8.10810811e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.56410256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 2.00000000e+00,  0.00000000e+00,  3.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         9.14285714e-01, -3.52941176e-01,  0.00000000e+00,
         0.00000000e+00,  1.21739130e+00,  3.07692308e+00,
         1.21739130e+00,  6.25049702e+00,  4.63087248e+00,
         2.87500000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.46835443e+00,  6.07407407e+00,
        -5.00000000e-01, -5.00000000e-01,  3.07692308e+00,
         1.35593220e+00, -9.39534884e-01,  1.13368125e+00,
         3.75000000e-01, -5.00000000e-01, -3.20000000e+00,
         2.90000000e+00,  3.07692308e-01,  1.13636364e+00,
         0.00000000e+00,  8.75000000e-01,  9.83555043e-01,
         1.53191489e+00,  1.87179487e+00, -6.66666667e-01,
         2.15686275e-01,  4.44674438e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  6.66666667e-01,  1.00000000e+00,
        -2.28571429e-01,  2.35294118e-01,  0.00000000e+00,
         0.00000000e+00, -1.04347826e+00, -6.15384615e-01,
        -1.04347826e+00, -1.20079523e+00, -7.38255034e-01,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        -3.33333333e-01, -8.10126582e-01, -5.92592593e-01,
        -5.00000000e-01, -5.00000000e-01,  0.00000000e+00,
        -2.48587571e-01, -1.38604651e+00, -7.51505420e-01,
        -6.25000000e-01,  0.00000000e+00, -3.20000000e+00,
         2.90000000e+00,  3.07692308e-01,  1.13636364e+00,
         0.00000000e+00,  8.75000000e-01,  9.83555043e-01,
         1.53191489e+00,  1.87179487e+00, -6.66666667e-01,
         2.15686275e-01,  4.44674438e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  0.00000000e+00,
         0.00000000e+00, -9.41176471e-01,  0.00000000e+00,
         0.00000000e+00, -6.95652174e-01, -7.38461538e-01,
        -6.95652174e-01, -1.21669980e+00, -9.53020134e-01,
        -5.00000000e-01,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -7.59493671e-01, -4.44444444e-01,
        -5.00000000e-01, -5.00000000e-01, -6.15384615e-01,
        -9.26553672e-01, -1.40465116e+00, -7.51505420e-01,
        -6.25000000e-01, -1.00000000e+00, -3.20000000e+00,
         2.90000000e+00,  3.07692308e-01,  1.13636364e+00,
         0.00000000e+00,  8.75000000e-01,  9.83555043e-01,
         1.53191489e+00,  1.87179487e+00, -6.66666667e-01,
         2.15686275e-01,  4.44674438e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.42857143e-01,  3.52941176e-01,  1.00000000e+00,
         0.00000000e+00, -8.69565217e-01,  8.00000000e-01,
        -8.69565217e-01,  1.66202783e+00,  1.97315436e+00,
         1.12500000e+00,  0.00000000e+00,  0.00000000e+00,
         6.66666667e-01,  1.87341772e+00,  2.81481481e+00,
         5.00000000e-01,  5.00000000e-01,  6.15384615e-01,
         1.62711864e+00, -4.00000000e-01, -1.92211963e+00,
        -1.37500000e+00,  2.50000000e+00, -4.00000000e+00,
        -5.30000000e+00, -1.23076923e+00, -1.31818182e+00,
        -5.40540541e-01, -2.00000000e+00, -3.38326176e+00,
        -7.65957447e+00, -6.43589744e+00, -2.57333333e+01,
        -3.74509804e+00, -1.09625249e+01],
       [ 1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         0.00000000e+00,  3.33333333e-01,  0.00000000e+00,
         0.00000000e+00,  3.52941176e-01,  0.00000000e+00,
         0.00000000e+00, -1.73913043e-01, -3.07692308e-01,
        -1.73913043e-01, -1.59045726e-01,  1.34228188e-02,
        -7.50000000e-01,  0.00000000e+00,  0.00000000e+00,
         6.66666667e-01, -5.06329114e-02,  4.44444444e-01,
        -5.00000000e-01,  5.00000000e-01,  0.00000000e+00,
         6.32768362e-01,  6.60465116e-01,  1.15134484e+00,
        -1.25000000e-01,  1.50000000e+00,  0.00000000e+00,
        -1.00000000e-01, -3.07692308e-01, -4.54545455e-02,
        -5.40540541e-01, -2.00000000e+00,  3.56132817e-01,
         1.27659574e+00, -2.56410256e-02, -2.66666667e-01,
         2.50980392e+00,  4.76087575e-01],
       [ 1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.33333333e-01,  0.00000000e+00,
         2.28571429e-01,  1.17647059e-01,  0.00000000e+00,
         1.00000000e+00,  3.47826087e-01,  6.76923077e-01,
         3.47826087e-01,  2.62425447e-01,  4.69798658e-01,
        -7.50000000e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.51898734e+00,  1.18518519e+00,
        -5.00000000e-01,  5.00000000e-01, -3.07692308e-01,
        -2.25988701e-01,  1.95348837e-01, -3.08309916e-01,
        -1.37500000e+00,  5.00000000e-01,  0.00000000e+00,
        -8.00000000e-01, -1.16923077e+00,  9.09090909e-03,
        -2.70270270e-01,  3.33333333e-01, -3.01665445e+00,
         0.00000000e+00, -1.51282051e+00,  5.33333333e-01,
        -1.84313725e+00,  2.57173728e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.66666667e-01,  1.00000000e+00,
         1.94285714e+00,  4.70588235e-01,  1.00000000e+00,
         0.00000000e+00,  3.47826087e-01,  1.23076923e-01,
         3.47826087e-01,  7.87276342e-01,  6.30872483e-01,
         5.00000000e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  7.08860759e-01,  1.18518519e+00,
        -5.00000000e-01, -5.00000000e-01,  3.07692308e-01,
         1.01694915e+00,  9.30232558e-03,  6.02167804e-01,
        -1.25000000e-01,  5.00000000e-01, -8.00000000e-01,
        -1.80000000e+00, -6.15384615e-01,  4.09090909e-01,
        -1.89189189e-01, -5.00000000e-01, -3.38326176e+00,
        -7.65957447e+00, -2.79487179e+00,  9.33333333e-01,
        -1.99019608e+00, -1.09625249e+01],
       [ 2.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         3.42857143e-01,  3.52941176e-01,  1.00000000e+00,
         0.00000000e+00, -1.73913043e-01,  2.46153846e-01,
        -1.73913043e-01,  2.54473161e-01,  6.71140940e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -3.33333333e-01,  3.03797468e-01,  1.48148148e-01,
         5.00000000e-01, -5.00000000e-01,  3.07692308e-01,
        -5.19774011e-01,  6.23255814e-01, -3.46848655e-01,
        -6.25000000e-01,  0.00000000e+00, -8.00000000e-01,
        -1.80000000e+00, -6.15384615e-01,  4.09090909e-01,
        -1.89189189e-01, -5.00000000e-01, -3.38326176e+00,
        -7.65957447e+00, -2.79487179e+00,  9.33333333e-01,
        -1.99019608e+00, -1.09625249e+01],
       [ 0.00000000e+00,  2.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.33333333e-01,  0.00000000e+00,
         9.14285714e-01, -5.88235294e-01,  0.00000000e+00,
         0.00000000e+00, -1.21739130e+00, -3.07692308e-01,
        -1.21739130e+00, -1.07355865e+00, -6.84563758e-01,
        -5.00000000e-01,  0.00000000e+00,  0.00000000e+00,
        -3.33333333e-01, -5.56962025e-01, -5.92592593e-01,
         5.00000000e-01,  5.00000000e-01, -6.15384615e-01,
        -9.26553672e-01, -4.55813953e-01, -3.46848655e-01,
        -6.25000000e-01,  0.00000000e+00, -8.00000000e-01,
        -1.80000000e+00, -6.15384615e-01,  4.09090909e-01,
        -1.89189189e-01, -5.00000000e-01, -3.38326176e+00,
        -7.65957447e+00, -2.79487179e+00,  9.33333333e-01,
        -1.99019608e+00, -1.09625249e+01]])

In [56]:
weight = pd.read_excel('weight.xlsx',sheet_name = 'Sheet2', index_col = '시설')
weight

                   여성20~34  전체65세이상  개인화
시설
체육시설                     2        3    1
도서관                      2        3    1
문화시설                     3        3    1
공원                       3        3    1
장애인복지시설                  0        0    0
어르신돌봄시설                  0        3    0
경로당                      0        3    0
사회복지시설                   0        3    0
전통시장                     2        3    1
백화점                      2        1    3
대형마트&슈퍼마켓                3        3    1
편의점                      3        1    1
세탁소                      2        1    3
식당                       3        1    1
카페                       3        1    1
헬스클럽                     2        0    3
영화관                      1        0    1
구청,동주민센터,보건소             1        3    0
공영주차장                    2        1    3
버스정류장                    3        3    0
공공자전거 대여소                3        0    0
파출소                      3        0    0
여성안심택배함                  3        0    0
심리상담센터                   3        0    0
병원                       1        3    3
CCTV                     3        0    3
개등록수                     2        0    3
고양이등록수                   2        0    3
동물병원                     2        0    3
원룸(보증금)                 -3        0    0
원룸(월세)                  -3        0    0
투룸.쓰리룸(보증금)              0       -3    0
투룸.쓰리룸(월세)               0       -3    0
오피스텔/도시형생활주택(보증금)       -3        0    0
오피스텔/도시형생활주택(월세)        -3        0    0
아파트(보증금)                 0        0    0
아파트(월세)                  0       -3    0
원룸(전세)                   0        0    0
투룸.쓰리룸(전세)               0       -3    0
오피스텔/도시형생활주택(전세)         0        0    0
아파트(전세)                  0       -3    3

In [61]:
output = np.dot(matrix_df,weight)
output = pd.DataFrame(output)
output.index = df['행정동']
output.columns = weight.columns
output

        여성20~34     전체65세이상        개인화
행정동
염창동   20.952199  -38.137246  25.697157
등촌1동  -0.790243    9.475009   2.967510
등촌2동 -28.677278  -10.495982 -14.146618
등촌3동  12.559411   36.722444  14.852652
화곡1동  62.817008   27.919369  60.764976
화곡2동 -21.086953  -11.225777  -9.770695
화곡3동  10.674958   19.107728   4.515689
화곡4동  -0.025821    1.322600   2.395327
화곡본동  24.122656   19.946197  23.737885
화곡6동  21.100027   15.235917  12.836401
화곡8동   5.162637    4.027937   6.493637
가양1동  98.399579   26.716606  52.068327
가양2동 -25.640258  -21.485801  -2.421533
가양3동 -30.279291  -27.840607  -6.973688
발산1동  67.806406  157.925743 -24.265656
우장산동  24.373732   10.924320  15.488030
공항동   17.860261    8.883311   9.623814
방화1동  25.834782   75.035475 -21.444787
방화2동  17.719769   63.663400 -33.620586
방화3동  -6.616010   48.944070 -47.385603

In [69]:
output_young = pd.DataFrame(output['여성20~34']).sort_values(by=['여성20~34'],axis =0, ascending=False)
output_old = pd.DataFrame(output['전체65세이상']).sort_values(by=['전체65세이상'],axis =0, ascending=False)
output_personalize = pd.DataFrame(output['개인화']).sort_values(by=['개인화'],axis =0, ascending=False)

In [73]:
output_young

        여성20~34
행정동
가양1동  98.399579
발산1동  67.806406
화곡1동  62.817008
방화1동  25.834782
우장산동  24.373732
화곡본동  24.122656
화곡6동  21.100027
염창동   20.952199
공항동   17.860261
방화2동  17.719769
등촌3동  12.559411
화곡3동  10.674958
화곡8동   5.162637
화곡4동  -0.025821
등촌1동  -0.790243
방화3동  -6.616010
화곡2동 -21.086953
가양2동 -25.640258
등촌2동 -28.677278
가양3동 -30.279291

In [74]:
output_old

         전체65세이상
행정동
발산1동  157.925743
방화1동   75.035475
방화2동   63.663400
방화3동   48.944070
등촌3동   36.722444
화곡1동   27.919369
가양1동   26.716606
화곡본동   19.946197
화곡3동   19.107728
화곡6동   15.235917
우장산동   10.924320
등촌1동    9.475009
공항동     8.883311
화곡8동    4.027937
화곡4동    1.322600
등촌2동  -10.495982
화곡2동  -11.225777
가양2동  -21.485801
가양3동  -27.840607
염창동   -38.137246

In [75]:
output_personalize

            개인화
행정동
화곡1동  60.764976
가양1동  52.068327
염창동   25.697157
화곡본동  23.737885
우장산동  15.488030
등촌3동  14.852652
화곡6동  12.836401
공항동    9.623814
화곡8동   6.493637
화곡3동   4.515689
등촌1동   2.967510
화곡4동   2.395327
가양2동  -2.421533
가양3동  -6.973688
화곡2동  -9.770695
등촌2동 -14.146618
방화1동 -21.444787
발산1동 -24.265656
방화2동 -33.620586
방화3동 -47.385603

In [39]:
# 저장하기
output.to_excel("output_all.xlsx", encoding='utf-8-sig')